# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

import app.resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(900, 550)
        MainWindow.setMinimumSize(QSize(900, 550))
        MainWindow.setMaximumSize(QSize(900, 550))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(75, 75, 75, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush2 = QBrush(QColor(120, 120, 120, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        MainWindow.setPalette(palette)
        font = QFont()
        font.setFamily(u"Times New Roman")
        font.setPointSize(14)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/icon/icon/caesar-cipher.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"")
        MainWindow.setIconSize(QSize(24, 24))
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 911, 551))
        font1 = QFont()
        font1.setFamily(u"Times New Roman")
        font1.setPointSize(12)
        font1.setBold(False)
        font1.setWeight(50)
        font1.setKerning(True)
        self.frame.setFont(font1)
        self.frame.setAutoFillBackground(True)
        self.frame.setStyleSheet(u"")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(9, 10, 881, 80))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.title = QLabel(self.frame_2)
        self.title.setObjectName(u"title")
        self.title.setGeometry(QRect(0, 0, 881, 81))
        font2 = QFont()
        font2.setFamily(u"Times New Roman")
        font2.setPointSize(24)
        font2.setBold(False)
        font2.setWeight(50)
        font2.setKerning(True)
        self.title.setFont(font2)
        self.title.setTextFormat(Qt.AutoText)
        self.title.setAlignment(Qt.AlignCenter)
        self.frame_3 = QFrame(self.frame)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(10, 110, 321, 431))
        self.frame_3.setMinimumSize(QSize(321, 431))
        self.frame_3.setMaximumSize(QSize(321, 431))
        self.frame_3.setStyleSheet(u"")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.scrollArea = QScrollArea(self.frame_3)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(0, 0, 321, 431))
        self.scrollArea.setMinimumSize(QSize(321, 431))
        self.scrollArea.setMaximumSize(QSize(321, 431))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 319, 429))
        self.scrollAreaWidgetContents.setMinimumSize(QSize(319, 429))
        self.scrollAreaWidgetContents.setMaximumSize(QSize(319, 429))
        self.INPUT_TEXT = QTextEdit(self.scrollAreaWidgetContents)
        self.INPUT_TEXT.setObjectName(u"INPUT_TEXT")
        self.INPUT_TEXT.setGeometry(QRect(0, 0, 321, 431))
        self.INPUT_TEXT.setMinimumSize(QSize(321, 431))
        self.INPUT_TEXT.setMaximumSize(QSize(321, 431))
        self.INPUT_TEXT.setFrameShadow(QFrame.Sunken)
        self.INPUT_TEXT.setAutoFormatting(QTextEdit.AutoAll)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_5 = QFrame(self.frame)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(420, 110, 131, 31))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.key = QSpinBox(self.frame_5)
        self.key.setObjectName(u"key")
        self.key.setGeometry(QRect(0, 0, 131, 31))
        self.key.setFont(font1)
        self.key.setMinimum(1)
        self.key.setMaximum(25)
        self.frame_6 = QFrame(self.frame)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(350, 110, 61, 31))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.label_key = QLabel(self.frame_6)
        self.label_key.setObjectName(u"label_key")
        self.label_key.setGeometry(QRect(0, 0, 61, 31))
        font3 = QFont()
        font3.setFamily(u"Times New Roman")
        font3.setPointSize(18)
        font3.setBold(False)
        font3.setWeight(50)
        font3.setKerning(True)
        self.label_key.setFont(font3)
        self.label_key.setAlignment(Qt.AlignCenter)
        self.frame_7 = QFrame(self.frame)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(350, 170, 211, 51))
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.btnEncrypt = QPushButton(self.frame_7)
        self.btnEncrypt.setObjectName(u"btnEncrypt")
        self.btnEncrypt.setGeometry(QRect(10, 0, 191, 51))
        self.btnEncrypt.setFont(font1)
        self.btnEncrypt.setStyleSheet(u"")
        icon1 = QIcon()
        icon1.addFile(u":/icon/icon/encrypt.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnEncrypt.setIcon(icon1)
        self.btnEncrypt.setIconSize(QSize(30, 30))
        self.btnEncrypt.setFlat(False)
        self.frame_8 = QFrame(self.frame)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(360, 240, 191, 51))
        self.frame_8.setAutoFillBackground(True)
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.btnDecrypt = QPushButton(self.frame_8)
        self.btnDecrypt.setObjectName(u"btnDecrypt")
        self.btnDecrypt.setGeometry(QRect(0, 0, 191, 51))
        self.btnDecrypt.setFont(font1)
        icon2 = QIcon()
        icon2.addFile(u":/icon/icon/decrypt.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnDecrypt.setIcon(icon2)
        self.btnDecrypt.setIconSize(QSize(30, 30))
        self.btnDecrypt.setFlat(False)
        self.frame_9 = QFrame(self.frame)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(350, 310, 201, 191))
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.btnImage = QPushButton(self.frame_9)
        self.btnImage.setObjectName(u"btnImage")
        self.btnImage.setEnabled(True)
        self.btnImage.setGeometry(QRect(0, 0, 201, 191))
        self.btnImage.setMinimumSize(QSize(201, 191))
        self.btnImage.setMaximumSize(QSize(201, 191))
        font4 = QFont()
        font4.setFamily(u"Times New Roman")
        font4.setPointSize(8)
        font4.setBold(False)
        font4.setWeight(50)
        font4.setKerning(True)
        self.btnImage.setFont(font4)
        self.btnImage.setMouseTracking(False)
        self.btnImage.setTabletTracking(False)
        self.btnImage.setStyleSheet(u"background: transparent;")
        self.btnImage.setInputMethodHints(Qt.ImhNone)
        self.btnImage.setIcon(icon)
        self.btnImage.setIconSize(QSize(215, 185))
        self.frame_4 = QFrame(self.frame)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(570, 110, 321, 431))
        self.frame_4.setMinimumSize(QSize(321, 431))
        self.frame_4.setMaximumSize(QSize(321, 431))
        self.frame_4.setStyleSheet(u"")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.scrollArea_2 = QScrollArea(self.frame_4)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setGeometry(QRect(0, 0, 321, 431))
        self.scrollArea_2.setMinimumSize(QSize(321, 431))
        self.scrollArea_2.setMaximumSize(QSize(321, 431))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 319, 429))
        self.scrollAreaWidgetContents_2.setMinimumSize(QSize(319, 429))
        self.scrollAreaWidgetContents_2.setMaximumSize(QSize(319, 429))
        self.OUTPUT_TEXT = QTextEdit(self.scrollAreaWidgetContents_2)
        self.OUTPUT_TEXT.setObjectName(u"OUTPUT_TEXT")
        self.OUTPUT_TEXT.setGeometry(QRect(0, 0, 321, 431))
        self.OUTPUT_TEXT.setMinimumSize(QSize(321, 431))
        self.OUTPUT_TEXT.setMaximumSize(QSize(321, 431))
        self.OUTPUT_TEXT.setFrameShadow(QFrame.Sunken)
        self.OUTPUT_TEXT.setAutoFormatting(QTextEdit.AutoAll)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_5.raise_()
        self.frame_6.raise_()
        self.frame_8.raise_()
        self.frame_7.raise_()
        self.frame_9.raise_()
        self.frame_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Cipher of Caesar", None))
        self.title.setText(QCoreApplication.translate("MainWindow", u"Cipher of Caesar", None))
        self.INPUT_TEXT.setPlaceholderText(QCoreApplication.translate("MainWindow", u"INPUT", None))
        self.label_key.setText(QCoreApplication.translate("MainWindow", u"Key:", None))
        self.btnEncrypt.setText(QCoreApplication.translate("MainWindow", u"Encrypt", None))
        self.btnDecrypt.setText(QCoreApplication.translate("MainWindow", u"Decrypt", None))
        self.btnImage.setText("")
        self.OUTPUT_TEXT.setPlaceholderText(QCoreApplication.translate("MainWindow", u"OUTUP", None))
    # retranslateUi

